import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :tcgm_web_app, TcgmWebAppWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [ip: {0, 0, 0, 0}, port: 4000],
  url: [host: "2001:41d0:304:300::6c75", port: 4000],
  server: true,
  check_origin: false,  # Make sure this is set as you need it (for development purposes)
  secret_key_base: "nRiIgIQXI1tGiBKfhvGM8+LmD8dPeCg9iv8AHgDZUeasZkBJuV9cppGrpGcTsptL"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: TcgmWebApp.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
