version: '3.8'
services:
  app:
    build: ./back/tcgm_web_app
    container_name: phoenix_app_1
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      SECRET_KEY_BASE: "bd1f441fdd4c5f9d84e2a898f2075b019bfcf4e1acbf5a8d24f4c1baf11e0d5f"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: my_db
    volumes:
      - postgres_data:/var/lib/postgresql/Data
    networks:
      - default
  
  react-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
