name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      id: run_tests
      run: |
        # Replace the following command with your test command
        echo "Running tests..."
        # Simulating a test result
        echo "::set-output name=success::true"
      
    - name: Send Discord notification
      if: always()
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_SHA: ${{ github.sha }}
        JOB_STATUS: ${{ job.status }}
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
              "username": "GitHub Actions",
              "content": "**Repository:** '${{ github.repository }}'\n**Commit SHA:** '${GITHUB_SHA}'\n**Job Status:** '${JOB_STATUS}'"
            }' \
        $DISCORD_WEBHOOK_URL
