name: Mirroring

on: push

jobs:
  to_epitech:
    name: Push to Epitech
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Mirror to Epitech
      uses: pixta-dev/repository-mirroring-action@v1.1.1
      with:
        target_repo_url:
          git@github.com:EpitechPromo2026/B-EIP-600-PAR-6-1-eiptek3-ulysse.villanueva.git
        ssh_private_key:
          ${{ secrets.EIPTEK3_SSH_PRIVATE_KEY }}

    - name: Send Discord notification
      if: always()
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_SHA: ${{ github.sha }}
        JOB_STATUS: ${{ job.status }}
        JOB_NAME: ${{ github.job }}
        REPO_NAME: ${{ github.repository }}
        COLOR: ${{ steps.set_color.outputs.color }}
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
              "username": "GitHub Actions",
              "embeds": [{
                "title": "GitHub Actions - '${REPO_NAME}'",
                "description": "Workflow **'${{ github.workflow }}'** run for commit **'${GITHUB_SHA}'**.",
                "color": '${COLOR}',
                "fields": [
                  {
                    "name": "Job",
                    "value": "'${JOB_NAME}'",
                    "inline": true
                  },
                  {
                    "name": "Status",
                    "value": "'${JOB_STATUS}'",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "GitHub Actions",
                  "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                },
                "timestamp": "'$(date --utc +%FT%TZ)'"
              }]
            }' \
        $DISCORD_WEBHOOK_URL
